/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.BookController;
import javax.swing.*;
import java.awt.*;
import javax.swing.border.MatteBorder;

/**
 *
 * @author User
 */
public class AddBookForm extends javax.swing.JFrame {
    private JTextField titleField, authorField, yearField, genreField, publisherField;
    private JTextArea contentArea;
    private JButton addButton;
    private JLabel background;

    /**
     * Creates new form AddBookForm
     */
    public AddBookForm() {
        setTitle("Add Book");
        setSize(600, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);

        // Set background
        ImageIcon bgIcon = new ImageIcon(getClass().getResource("/Image/DA.png"));
        Image img = bgIcon.getImage().getScaledInstance(600, 500, Image.SCALE_SMOOTH);
        background = new JLabel(new ImageIcon(img));
        background.setBounds(0, 0, 600, 500);

        Color borderColor = new Color(0, 102, 153); // Dark blue
        Color textColor = Color.WHITE;

        // Title
        titleField = createStyledTextField(200, 126, 250, 20, borderColor, textColor);
        add(titleField);

        // Author
        authorField = createStyledTextField(200, 186, 250, 20, borderColor, textColor);
        add(authorField);

        // Year
        yearField = createStyledTextField(200, 244, 250, 20, borderColor, textColor);
        add(yearField);

        // Genre
        genreField = createStyledTextField(200, 305, 250, 20, borderColor, textColor);
        add(genreField);

        // Publisher
        publisherField = createStyledTextField(200, 363, 250, 20, borderColor, textColor);
        add(publisherField);

        // Content
        contentArea = new JTextArea();
        contentArea.setBounds(200, 400, 250, 60);
        contentArea.setFont(new Font("Arial", Font.PLAIN, 12));
        contentArea.setForeground(textColor);
        contentArea.setOpaque(false);
        contentArea.setBorder(new MatteBorder(0, 0, 1, 0, borderColor));
        contentArea.setCaretColor(textColor);
        add(contentArea);

        // Add Button
        addButton = new JButton("Add Book");
        addButton.setBounds(430, 400, 10, 40);
        addButton.setFont(new Font("Arial", Font.BOLD, 12));
        addButton.setForeground(Color.WHITE);
        addButton.setBackground(new Color(0, 51, 102));
        addButton.setFocusPainted(false);
        add(addButton);

        // Event
        addButton.addActionListener(e -> addBook());

        add(background);
        setVisible(true);
    }

    private JTextField createStyledTextField(int x, int y, int w, int h, Color borderColor, Color textColor) {
        JTextField field = new JTextField();
        field.setBounds(x, y, w, h);
        field.setOpaque(false);
        field.setForeground(textColor);
        field.setCaretColor(textColor);
        field.setFont(new Font("Arial", Font.PLAIN, 12));
        field.setBorder(new MatteBorder(0, 0, 1, 0, borderColor));
        return field;
    }

    private void addBook() {
        try {
            String title = titleField.getText();
            String author = authorField.getText();
            int year = Integer.parseInt(yearField.getText());
            String genre = genreField.getText();
            String publisher = publisherField.getText();
            String content = contentArea.getText();

            BookController bookController = new BookController();
            if (bookController.addBook(title, author, year, genre, publisher, content)) {
                JOptionPane.showMessageDialog(this, "Book added successfully!");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error adding book.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid year.");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
