/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import models.BorrowRecord;

/**
 *
 * @author User
 */
public class BarrowReturn extends javax.swing.JFrame {
    private JTextField bookIdField, userIdField;
    private JButton borrowButton, returnButton;
    private JTextArea recordsArea;
    /**
     * Creates new form BarrowReturn
     */
    
    public BarrowReturn() {
        setTitle("Borrow & Return Book");
        setSize(400, 300);
        setLayout(new FlowLayout());
        setLocationRelativeTo(null);

        add(new JLabel("Book ID:"));
        bookIdField = new JTextField(10);
        add(bookIdField);

        add(new JLabel("Email:"));
        userIdField = new JTextField(10);
        add(userIdField);

        borrowButton = new JButton("Borrow");
        returnButton = new JButton("Return");
        add(borrowButton);
        add(returnButton);

        recordsArea = new JTextArea(10, 30);
        recordsArea.setEditable(false);
        add(new JScrollPane(recordsArea));

        borrowButton.addActionListener(e -> borrowBook());
        returnButton.addActionListener(e -> returnBook());

        setVisible(true);
    }

    private void borrowBook() {
        String bookId = bookIdField.getText();
    String userId = userIdField.getText();

    if (BorrowRecord.borrowBook(userId, bookId)) {
        JOptionPane.showMessageDialog(this, "Book borrowed successfully.");
    } else {
        JOptionPane.showMessageDialog(this, "This book is already borrowed.");
    }
    updateRecordsDisplay();
}

    private void returnBook() {
        String bookId = bookIdField.getText();
    String userId = userIdField.getText();

    if (BorrowRecord.returnBook(userId, bookId)) {
        JOptionPane.showMessageDialog(this, "Book returned successfully.");
    } else {
        JOptionPane.showMessageDialog(this, "You can't return this book (maybe it wasn't borrowed or it's not yours).");
    }
    updateRecordsDisplay();
}
    private void updateRecordsDisplay() {
        ArrayList<String> records = BorrowRecord.getRecords();
        recordsArea.setText("");
        for (String record : records) {
            recordsArea.append(record + "\n");
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarrowReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarrowReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarrowReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarrowReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarrowReturn().setVisible(true);
            }
        });
    }

    private void addRecordLabel(int bookId, int i, int y) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
