/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import controllers.LoginController;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author User
 */
public class LoginForm extends javax.swing.JFrame {
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JButton loginButton, registerButton;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
         setTitle("Library Login");
        setSize(400, 500); // Adjusted size
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        
        JPanel formPanel = new JPanel();
        formPanel.setLayout(null); // Absolute positioning
        formPanel.setBackground(new Color(200, 200, 255)); // Light purple background
        
        JLabel logoLabel = new JLabel(new ImageIcon("C:/Users/User/Downloads/login_form-removebg-preview.png")); // Change path
        logoLabel.setBounds(120, 20, 150, 150); // Position of the logo
        formPanel.add(logoLabel);

        JLabel userLabel = new JLabel("Username:");
        userLabel.setBounds(50, 190, 100, 25);
        formPanel.add(userLabel);

        JTextField userField = new JTextField();
        userField.setBounds(150, 190, 180, 25);
        formPanel.add(userField);

        // Password Label & Field
        JLabel passLabel = new JLabel("Password:");
        passLabel.setBounds(50, 230, 100, 25);
        formPanel.add(passLabel);

        JPasswordField passField = new JPasswordField();
        passField.setBounds(150, 230, 180, 25);
        formPanel.add(passField);

        // Login Button
        JButton loginButton = new JButton("Login >>");
        loginButton.setBounds(100, 300, 200, 40);
        loginButton.setFont(new Font("Arial", Font.BOLD, 16));
        loginButton.setBackground(Color.WHITE);
        loginButton.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        formPanel.add(loginButton);

        // Register Button (New)
        JButton registerButton = new JButton("Register");
        registerButton.setBounds(100, 350, 200, 30);
        registerButton.setBackground(Color.WHITE);
        registerButton.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        formPanel.add(registerButton);

        // Add formPanel to frame
        add(formPanel, BorderLayout.CENTER);

        // Event handling
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, "Login clicked!");
                // Add login logic here
            }
        });

        registerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, "Go to Register Form");
                // Open RegisterForm here
            }
        });

        setVisible(true);
    }

    private void loginUser() {
        String studentNumber = usernameField.getText();
        String password = new String(passwordField.getPassword());

        LoginController controller = new LoginController();
        if (controller.loginUser(studentNumber, password)) {
            JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new MainForm(studentNumber);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid student number or password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void openRegisterForm() {
        this.dispose();
        new RegisterForm();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         new LoginForm();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
