/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.BookController;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author User
 */
public class RemoveBookForm extends javax.swing.JFrame {
    private JTextField bookIdField;
    private JButton removeButton;


    /**
     * Creates new form RemoveBookForm
     */
    public RemoveBookForm() {
        setTitle("Remove Book");
        setSize(300, 195);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Center the window

        // Load and scale the background image
        ImageIcon bgIcon = new ImageIcon(getClass().getResource("/Image/ARE.png"));
        Image img = bgIcon.getImage().getScaledInstance(300, 165, Image.SCALE_SMOOTH);
        JLabel background = new JLabel(new ImageIcon(img));
        background.setLayout(null); // Absolute layout for precise positioning

        // Create and position components
        JLabel bookIdLabel = new JLabel("Book ID:");
        bookIdLabel.setBounds(30, 70, 60, 25);
        background.add(bookIdLabel);

        bookIdField = new JTextField(10);
        bookIdField.setBounds(90, 70, 100, 25);
        background.add(bookIdField);

        removeButton = new JButton("Remove");
        removeButton.setBounds(200, 70, 80, 25);
        background.add(removeButton);

        removeButton.addActionListener(e -> removeBook());

        setContentPane(background);
        setResizable(false);
        setVisible(true);
    }

    


    private void removeBook() {
        int bookId = Integer.parseInt(bookIdField.getText());
        BookController bookController = new BookController();

        if (bookController.removeBook(bookId)) {
            JOptionPane.showMessageDialog(this, "Book removed successfully!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error removing book.");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
