/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class StudentInfoForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentInfoForm
     */
    public StudentInfoForm() {
        setTitle("Login");
        setSize(510, 355); // Match image size
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null); 
        
        // Load Background Image
        ImageIcon bgIcon = new ImageIcon(getClass().getResource("/Image/sda.png"));
        JLabel background = new JLabel();
        background.setIcon(bgIcon);
        background.setBounds(0, 0, 510, 355); // Set to image size
        
        // Labels
        JLabel userLabel = new JLabel("Username:");
        userLabel.setBounds(100, 100, 100, 20);
        userLabel.setFont(new Font("Arial", Font.BOLD, 12));
        userLabel.setForeground(Color.BLACK);
        add(userLabel);

        JLabel passLabel = new JLabel("Password:");
        passLabel.setBounds(100, 130, 100, 20);
        passLabel.setFont(new Font("Arial", Font.BOLD, 12));
        passLabel.setForeground(Color.BLACK);
        add(passLabel);

        JLabel emailLabel = new JLabel("Email:");
        emailLabel.setBounds(100, 160, 100, 20);
        emailLabel.setFont(new Font("Arial", Font.BOLD, 12));
        emailLabel.setForeground(Color.BLACK);
        add(emailLabel);

        // Buttons
        JButton changeUsernameBtn = new JButton("Change Username");
        changeUsernameBtn.setBounds(200, 100, 160, 20);
        add(changeUsernameBtn);

        JButton changePasswordBtn = new JButton("Change Password");
        changePasswordBtn.setBounds(200, 130, 160, 20);
        add(changePasswordBtn);

        JButton changeEmailBtn = new JButton("Change Email");
        changeEmailBtn.setBounds(200, 160, 160, 20);
        add(changeEmailBtn);
        
        // Back button
        JButton BackBtn = new JButton("Back");
        BackBtn.setBounds(380, 250, 70, 20);
        add(BackBtn);
        
        BackBtn.addActionListener(e -> {
            dispose(); // Closes the current StudentInfoForm
        });

        // Add background last so it's behind all components
        add(background);
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfoForm().setVisible(true);
            }
        });
    }

    private void MainForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
